CREATE TABLE `users` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `country` varchar(3) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `login` varchar(30) NOT NULL,
  `password` varchar(64) NOT NULL,
  `reg_date` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `login_UNIQUE` (`login`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `volunteers` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `userID` int(6) unsigned NOT NULL,
  `reg_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` varchar(60) DEFAULT NULL,
  `country` varchar(3) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `phone` varchar(15) DEFAULT NULL,
  `gender` varchar(1) DEFAULT NULL,
  `birthdate` date DEFAULT NULL,
  `nickname` varchar(30) DEFAULT NULL,
  `license` tinyint(1) DEFAULT 0,
  `footO` tinyint(1) DEFAULT NULL,
  `skiO` tinyint(1) DEFAULT NULL,
  `mtbO` tinyint(1) DEFAULT NULL,
  `trailO` tinyint(1) DEFAULT NULL,
  `startO` int(11) DEFAULT NULL,
  `club` varchar(60) DEFAULT NULL,
  `competitorExp` json DEFAULT NULL,
  `languages` json DEFAULT NULL,
  `preferredContinents` json DEFAULT NULL,
  `timeToStart` date DEFAULT NULL,
  `maxWorkDuration` int(11) DEFAULT NULL,
  `mappingSkilled` tinyint(1) DEFAULT NULL,
  `coachSkilled` tinyint(1) DEFAULT NULL,
  `itSkilled` tinyint(1) DEFAULT NULL,
  `eventSkilled` tinyint(1) DEFAULT NULL,
  `teacherSkilled` tinyint(1) DEFAULT NULL,
  `mappingDesc` json DEFAULT NULL,
  `coachDesc` json DEFAULT NULL,
  `itDesc` json DEFAULT NULL,
  `eventDesc` json DEFAULT NULL,
  `teacherDesc` json DEFAULT NULL,
  `otherSkills` longtext,
  `oworkLocalExp` json DEFAULT NULL,
  `oworkInternationalExp` json DEFAULT NULL,
  `helpDesc` longtext,
  `expectations` longtext,
  `abroadExp` longtext,
  `learning` longtext,
  PRIMARY KEY (`id`),
  KEY `user` (`userID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `maps` (
  id INT(6) AUTO_INCREMENT,
  map LONGBLOB,
  vid INT(5),
  PRIMARY KEY (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;
